FROM clearlinux:latest
ENV PATH=/usr/bin/haswell:/usr/local/bin:/usr/bin:/opt/3rd-party/bundles/clearfraction/usr/bin:/opt/3rd-party/bundles/clearfraction/usr/local/bin \
    LD_LIBRARY_PATH=/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/local/lib64 \
    XDG_DATA_DIRS=/usr/local/share/:/usr/share/:/opt/3rd-party/bundles/clearfraction/usr/share/:/opt/3rd-party/bundles/clearfraction/usr/local/share/ \
    XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg:/opt/3rd-party/bundles/clearfraction/usr/share/xdg:/opt/3rd-party/bundles/clearfraction/etc/xdg \
    FONTCONFIG_PATH=/usr/share/defaults/fonts

RUN swupd bundle-add lib-opengl gdk-pixbuf pulseaudio mpg123 dhcp-server openldap -y && \
    swupd 3rd-party add clearfraction https://download.clearfraction.cf/update -y && \
    swupd 3rd-party bundle-add codecs-cuda -y && \
    swupd 3rd-party clean --all && swupd clean --all
    
ENTRYPOINT  ["/opt/3rd-party/bundles/clearfraction/usr/local/bin/ffmpeg"]
